### ISSUE TITLE
Broken for IntelliJ 13

### ISSUE THREAD

**Issue by BourneLoser** [wonder-mice/mac-java-launcher#2]
```
./use --apply "/Applications/IntelliJ IDEA 13 CE.app"
applying launcher to "/Applications/IntelliJ IDEA 13 CE.app"
Error: Not a java application
```

I don't see a "Java" section in the Info.plist file yet the following dialog box pops up when I try to launch the application normally by clicking on it: "To open IntelliJ IDEA you need a Java SE 6 runtime. Would you like to install one now?"

IntelliJ IDEA 13.1.3
Mac OSX 10.9.3

**Comment by imranansari** [comment]
I'm getting the same error on OSX 10.10 and RubyMine

**Comment by wonder-mice** [comment]
Java section is removed from Info.plist. You need to modify Info.plist.original to change Java version.
Also, problem with IntelliJ is fixed now.
