### ISSUE TITLE
Add support for only changing the JVMVersion

### ISSUE THREAD

**Issue by pickypg** [wonder-mice/mac-java-launcher#5]
Similar to #1 and #2, you should consider making a version that only modifies the `Info.plist` file to update the `JVMVersion`.

I realize it's a simple change, but a lot of people aren't as comfortable doing it themselves.

PS: Otherwise a nice script!

**Comment by wonder-mice** [comment]
You can do it now with "--java-version" option.
"--java-version" option is a standalone option and you can use it without "--apply" or "--undo".

**Comment by pickypg** [comment]
Oh good! I thought that based on the code, but I don't know enough about Python to know how `app_dir` is set in that case. How do you supply the app bundle?

Maybe add an example to do _just_ this?

**Comment by wonder-mice** [comment]
Options format is:
[actions] bundle1, bundle2, bundle3, ...
Actions could be: --apply, --undo, --java-version.
You can't both apply and undo though.

**Comment by pickypg** [comment]
Cool, I made a PR to add this to the README. Feel free to change it as you see fit! Thanks for the script!
